### ISSUE TITLE
Works on ARM

### ISSUE THREAD

**Issue by FLYBYME** [progrium/go-basher#10]
Does anyone know if this works on ARM?

**Comment by progrium** [comment]
Go works on ARM. Just need an ARM Bash to go with it.

**Comment by FLYBYME** [comment]
Running on arm your code has no error checking.

https://github.com/progrium/go-basher/blob/3321ddc36cac3290fefc851285d40348b1f69b5b/basher.go#L245

**Comment by progrium** [comment]
You mean there is no error checking and ARM throws an error there?
