### ISSUE TITLE
Support for windows using win-bash

### ISSUE THREAD

**Issue by microstacks** [progrium/go-basher#12]
go-basher is neat, however adding win-bash would make this really powerful project. (http://win-bash.sourceforge.net/).

**Comment by josegonzalez** [comment]
I don't think anyone here has a windows machine to even begin working on this, let alone testing it. Have you tried checking if it works as is?

**Comment by athakwani** [comment]
Tested on windows 10 enterprise, seems to be working. However the bash version is very old and seems useless.

C:\shell.w32-ix86>bash -version
bash$ exit
exit
GNU bash, version win-bash_0.8.5(0)

**Comment by microstacks** [comment]
Linux subsystem on windows is way to go. Closing this issue.
