### ISSUE TITLE
Cannot execute the binary on RHEL

### ISSUE THREAD

**Issue by athakwani** [progrium/go-basher#13]
I am getting below error while running this on RHEL box. The binary is working fine on Mac and Ubuntu machines.

/tmp/bashenv.235468405: line 35: syntax error near unexpected token `('

/tmp/bashenv.235468405: line 35: `export BASH_FUNC_module()=$'() {  eval `/usr/bin/modulecmd bash $*`'

Any idea whats wrong here?

**Comment by josegonzalez** [comment]
What version of bash is running on your RHEL instance?

**Comment by athakwani** [comment]
GNU bash, version 4.1.2(1)-release-(x86_64-redhat-linux-gnu)
Usage:  bash [GNU long option] [option] ...
        bash [GNU long option] [option] script-file ...

**Comment by athakwani** [comment]
@josegonzalez any update on this?

**Comment by josegonzalez** [comment]
Not sure, do you have a reproduction you can show us so I can test it out?

**Comment by athakwani** [comment]
The machine was setup by IT so don't know what could be causing this. Any suggestions for workaround?

**Comment by josegonzalez** [comment]
If you have a bit of code that reproduces the issue, I can try it out on an RHEL vm.

**Comment by josegonzalez** [comment]
Closing as a repro wasn't given and there hasn't been feedback in a few months.
