### ISSUE TITLE
How to publish as a package?

### ISSUE THREAD

**Issue by toshi0383** [progrium/go-basher#14]
Hi there,

I added go-basher to my command, and have install issue.
https://github.com/toshi0383/ipanema/issues/9

Any idea?

**Comment by josegonzalez** [comment]
Sorry for not following up. This might be that you are compiling for or on Windows, as we don't have a `bash_windows.go`.

Let me know if you were able to get through this.

**Comment by toshi0383** [comment]
I'm not using Windows🤨

**Comment by josegonzalez** [comment]
Ah I see whats missing, you didn't pack your `bash` directory as shown [here](https://github.com/progrium/go-basher#using-go-basher-with-go-bindata).

I did the following:

```
cd ~
# get go-bindata binary
go get github.com/jteeuwen/go-bindata/...

# cd to your source code
cd go/src/github.com/toshi0383/ipanema

# pack your bash directory
go-bindata bash

# build the binary
go build
```
