### ISSUE TITLE
How do we ensure miscellaneous commands(curl .. etc ) are installed?

### ISSUE THREAD

**Issue by aero** [progrium/go-basher#21]
From the examples
https://github.com/progrium/go-basher/blob/6a5b35fcdaea1ddfc145720efc903869413629e7/example/bash/example.bash#L10

How do we ensure curl is installed on a system?
I like your idea.
But we can not assume all misc. commands are installed on a system except bash builin functions.

For fully safe portables binaries,
I think binary shoud include all dependent commands(32bit binary) like busybox.

If go-basher include 32bit statically compiled bash, busybox binaries and using only bash builtins + busybox supported commands, we can say it is fully self-executable binary.

**Comment by josegonzalez** [comment]
To do this, you can pack a statically compiled version of the tools you need, as done [here](https://github.com/progrium/go-basher/blob/master/Makefile#L15). Your usage of go-basher would then extract those tools as necessary and place them in the PATH of your code. You should also take care to cleanup any exported binaries.

Hope that helps.
