### ISSUE TITLE
Go + bash syntax

### ISSUE THREAD

**Issue by antonmedv** [progrium/go-basher#24]
Hi,

What about making bash + go syntax?

```bash
#!basher

export VAR=1

import "fmt"

func print_something (foo string) {
    fmt.Println(foo, $VAR);
}

print_something Mars
print_something Jupiter
```

**Comment by antonmedv** [comment]
This will be the best way to use bash+go together. The only difficult part is to split go from bash. 

But I think this is possible to do, just need to write custom parser what parses this "language", then visitor pattern finds go parts.

**Comment by josegonzalez** [comment]
That seems like a new language? Which is a bit outside of the scope of this project. Might be a cool thing for you to work on as an OSS project though :)
