### ISSUE TITLE
An example on how to use the basher.Application() function?

### ISSUE THREAD

**Issue by shrinidhi111** [progrium/go-basher#36]
I understand that this can be used in situations where we are not exactly sure if `/bin/bash` is available in the system or not.

But I'm not able to figure out how to use this function.

It would be great if someone can give an example!

**Comment by josegonzalez** [comment]
The `plugn` project just uses it like this:

https://github.com/dokku/plugn/blob/master/plugn.go#L105-L109

```go
if os.Getenv("BASH_BIN") == "" {
	basher.Application(funcs, scripts, Asset, true)
} else {
	basher.ApplicationWithPath(funcs, scripts, Asset, true, os.Getenv("BASH_BIN"))
}
```

There isn't anything special here. The `bash` binary is extracted and then referenced when executing the script.
