### ISSUE TITLE
cannot use reverse (type func([]string) int) as type

### ISSUE THREAD

**Issue by saz59** [progrium/go-basher#4]
# github.com/progrium/go-basher/example

./example.go:45: cannot use reverse (type func([]string) int) as type func([]string) in argument to bash.ExportFunc
./example.go:46: cannot use jsonPointer (type func([]string) int) as type func([]string) in argument to bash.ExportFunc
make: **\* [build] Error 2

**Comment by progrium** [comment]
Oh, the example app is out of date I guess? Thanks
