### ISSUE TITLE
plugn-bashenv######### files filling /tmp filesystem

### ISSUE THREAD

**Issue by u2mejc** [progrium/go-basher#9]
plugn-bashenv######### files are not expunged from /tmp/ and are added for every execution.

This was orignally reported for https://github.com/progrium/plugn/issues/6 and was opened here at the request of @progrium.

**Comment by lalyos** [comment]
Hi @u2mejc 

The bashenv.#### files are kept if you have the `DEBUG` env variable set.
Please check if after `unset DEBUG` the issue is still happening.

**Comment by u2mejc** [comment]
Closing as I believe we have identified this as Dokku / plugn using an older version.
